services:
  postgres:
    image: postgres:16-alpine
    container_name: atr_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: audit_core_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - atr_network

volumes:
  postgres_data:

networks:
  atr_network:
    driver: bridge
